export default function ProjectsDetails() {
	return [
		/* projects */
		{
			name: 'Betrayal at House on the Hill Helper',
			category: 'projects',
			tags: ['semantic-ui', 'js', 'helper'],
			icon: 'betrayalhelper.png',
			page: '',
			linkTo: 'http://www.elementten.com/BetrayalHelper/',
		},
		{
			name: 'MentorWeb',
			category: 'projects',
			tags: ['angular-js', 'js', 'css', 'html', 'agile'],
			icon: 'mentorweb.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Robocop Dispatch Interface',
			category: 'projects',
			tags: ['game', 'flash'],
			icon: 'robocop.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Atlanta Civic Dashboard',
			category: 'projects',
			tags: ['js', 'civics', 'gridster', 'ALS', 'visualization'],
			icon: 'atlcivicdashboard.png',
			page: '',
			linkTo: '',
		},


		/* games */
		{
			name: 'Perspective',
			category: 'games',
			tags: ['game', 'unity'],
			icon: 'perspectivegame.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Tower of Dormin',
			category: 'games',
			tags: ['game', 'flash'],
			icon: 'towerofdormin.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Quietus',
			category: 'games',
			tags: ['game', 'unity'],
			icon: 'quietus.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Survivor',
			category: 'games',
			tags: ['game', 'c#'],
			icon: 'survivorgame.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Pong Revolutions',
			category: 'games',
			tags: ['game', 'flash'],
			icon: 'pongrevolutions.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'I\'m Going to Rain in Your Volcano',
			category: 'games',
			tags: ['game', 'flash'],
			icon: 'rainvolcano.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Want Everything',
			category: 'games',
			tags: ['game', 'flash'],
			icon: 'wanteverything.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Skyfall',
			category: 'games',
			tags: ['game', 'unity'],
			icon: 'skyfall.png',
			page: '',
			linkTo: '',
		},

		/* designs */
		{
			name: 'Text Messaging Steps',
			category: 'projects',
			tags: ['illustrator'],
			icon: 'textposter.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Work Ready Grad Videos',
			category: 'projects',
			tags: ['flash', 'video'],
			icon: 'workreadygrad.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Fastshop',
			category: 'projects',
			tags: ['flash', 'video'],
			icon: 'fastshop.png',
			page: '',
			linkTo: '',
		},
		{
			name: 'Tiamat Media',
			category: 'projects',
			tags: ['photoshop'],
			icon: 'tiamatmedia.png',
			page: '',
			linkTo: '',
		},
	];
}